<?php

namespace api\modules\v1\models;

use Yii;
use yii\base\Security;
use yii\web\UploadedFile;

/**
 * This is the model class for table "attachments".
 *
 * @property int $id
 * @property int $user_id
 * @property string $comment
 * @property string $image
 * @property string $_image
 * @property int $status
 * @property int $date
 * @property int $category_id
 * @property int $group_kay
 */
class Attachments extends \yii\db\ActiveRecord
{
    /**
     * @var UploadedFile
     */
    public $_image;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'attachments';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['_image'], 'file', 'extensions' => 'png, jpg'],
            [['user_id', 'status', 'category_id'], 'integer'],
            [['comment', 'image', 'date', 'group_kay'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User',
            'comment' => 'Comment',
            'image' => 'Image',
            'status' => 'Status',
            'date' => 'date',
            'category_id' => 'category_id',
            'group_kay' => 'group_kay',
        ];
    }

    public function beforeSave($insert)
    {
        $this->date = date('Y-m-d');
        $this->user_id = Yii::$app->user->identity->getId();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function upload($type)
    {
        $last_data = self::find()->orderBy(['id' => SORT_DESC])->one();
        if (!empty($this->_image)) {
            $img_name = self::GetName($type, $last_data) . '.' . $this->_image->extension;
            if ($this->_image->saveAs(Yii::getAlias('@frontend') . '/web/attachments/' . $img_name)) {
                return $img_name;
            }
        }
        return false;
    }

    public static function GetAttachments()
    {
        return self::find()
            ->where(['user_id' => Yii::$app->user->identity->getId()])
            ->asArray()
            ->orderBy(['id' => SORT_DESC])
            ->all();
    }

    public static function SendEmail($model)
    {
        return Yii::$app
            ->mailer
            ->compose(
                ['html' => 'attachment-html', 'text' => 'attachment-text'],
                [
                    'model' => $model,
                    'user' => Yii::$app->user->identity,
                ]
            )
            ->setFrom(['davit@gmail.com' => Yii::$app->user->identity->first_name . ' ' . Yii::$app->user->identity->last_name])
            ->setTo(Yii::$app->params['adminEmail'])
            ->setSubject(Yii::$app->params['subject_attachment'])
            ->send();
    }

    public static function GetName($type, $last_data)
    {
//        FP-040119-REALMID-587.jpg
        $t = $type == 0 ? 'FP' : 'FA';
        return $t . '-' . date('dmY') . '-' . Yii::$app->user->identity->realm_id . '-' . ($last_data['id'] * 1 + 1);

    }
}
